CREATE TABLE IF NOT EXISTS content (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    genre TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    youtube_video_id VARCHAR(50),
    view_count INTEGER DEFAULT 0,
    published_at TIMESTAMP
);

