CREATE TABLE SECRETS (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    api_url TEXT NOT NULL,
    api_key TEXT NOT NULL,
    model_name TEXT NOT NULL,
    role_key TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

